apiVersion: monitoring.hugh.local/v1alpha1
kind: HealthPolicy
metadata:
  labels:
    app.kubernetes.io/name: k8s-health-operator
    app.kubernetes.io/managed-by: kustomize
  name: healthpolicy-sample
spec:
  namespaces:
    - default
  crashLoopThreshold: 3
  reportingInterval: 30s
  pendingPodThreshold: 2m
